services:
  - type: web
    name: python-code-editor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    autoDeploy: true